version: 0.0
os: linux
files:
  - source: /index.html
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: preinstall.sh
      runas: root
  AfterInstall:
    - location: postinstall.sh
      runas: root
