version: 0.0
os: linux
files:
  - source: /index.html
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/preinstall1
      runas: root
  AfterInstall:
    - location: scripts/postinstall1
      runas: root
